### ISSUE TITLE
第5章 レイアウトを作成する

### ISSUE THREAD

**Issue by saran12345678** [saran12345678/RubyonRailsTutorial#5]
### Webページと言ったらネコ画像、というぐらいにはWebにはネコ画像が溢れていますよね。[リスト 5.4](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#code-downloading_a_cat_pic)のコマンドを使って、[図 5.3](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#fig-kitten)のネコ画像をダウンロードしてきましょう[11](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#cha-5_footnote-11) 。
コマンド
```
curl -OL https://cdn.learnenough.com/kitten.jpg
```

### mvコマンドを使って、ダウンロードしたkitten.jpgファイルを適切なアセットディレクトリに移動してください（参考: [5.2.1](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#sec-the_asset_pipeline)）。
```
mv kitten.jpg app/assets/images
```

### image_tagを使って、kitten.jpg画像を表示してみてください（[図 5.4](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#fig-kitten_on_home)）。
```
<%= link_to image_tag("kitten.jpg", alt: "Cat image", width: "200")%>
```
<img width="580" alt="スクリーンショット 2024-08-28 10 07 54" src="https://github.com/user-attachments/assets/d273a1b3-3a7e-44d5-93b3-44debce2d069">

**Comment by saran12345678** [comment]
### [リスト 5.10](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#code-comment_out_image)を参考にして、[5.1.1.1](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#sec-exercises_adding_to_the_layout)の演習で使ったネコ画像をコメントアウトしてみてください。また、ブラウザのHTMLインスペクタ機能を使って、コメントアウトするとHTMLのソースからも消えていることを確認してみてください。
猫の画像をコメントアウトする
　このコメントアウトではソースが表示されてしまうため注意
コメントとして残ってしまう。
```
<%#= link_to image_tag("kitten.jpg", alt: "Cat image", width: "200")%>
```
猫画像が表示されないことを確認
<img width="759" alt="スクリーンショット 2024-08-28 10 49 30" src="https://github.com/user-attachments/assets/1bca092d-f604-46a1-92a3-1aa51d527f30">

コメントアウトされたソースが表示されなくなっている。
<img width="484" alt="スクリーンショット 2024-08-28 11 06 29" src="https://github.com/user-attachments/assets/7fdea18b-94b3-4934-b57e-06894e48fb3e">


### [リスト 5.11](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#code-css_hide_image)のコードをcustom.scssに追加し、すべての画像を非表示にしてみてください。うまくいけば、Railsのロゴ画像がHomeページから消えるはずです。先ほどと同様にインスペクタ機能を使って、今度はHTMLのソースコードは残ったままで、画像だけが表示されなくなっていることを確認してみてください。この演習による変更は、終わった後必ず元に戻してください（そうしないとこの後の画像が正しく表示されません）。
画像が表示されないことを確認
<img width="1147" alt="スクリーンショット 2024-08-28 11 03 40" src="https://github.com/user-attachments/assets/44e14dd6-61e0-4f1c-80c3-1b8da6aeb242">

ロゴのソースが残っていることを確認
<img width="527" alt="スクリーンショット 2024-08-28 11 04 46" src="https://github.com/user-attachments/assets/c54d504a-8f05-4d13-973f-374986cceb36">

**Comment by saran12345678** [comment]
### Railsがデフォルトで生成するheadタグの部分を、[リスト 5.17](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#code-rails_default_head)のようにrenderに置き換えてみてください。（ヒント: 単純に削除してしまうと後でパーシャルを1から書き直す必要が出てくるので、削除する前にどこかに退避しておきましょう。）
```html
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= render 'layouts/rails_default' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>
```

### [リスト 5.17](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#code-rails_default_head)のようなパーシャルはまだ作っていないので、現時点ではテストは red になっているはずです。実際にテストを実行して確認してみましょう。
テストに失敗することを確認。
```
5 runs, 0 assertions, 0 failures, 5 errors, 0 skips
```

### layoutsディレクトリにheadタグ用のパーシャルを作成し、先ほど退避しておいたコードを書き込み、最後にテストが green に戻ることを確認しましょう。
_rails_default.html.erbを作成することでテストが成功するようになったことを確認。
```
5 runs, 0 assertions, 0 failures, 5 errors, 0 skips
```

**Comment by saran12345678** [comment]
### [5.2.2](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#sec-sass)で提案したように、footerのCSSを手作業で変換してみましょう。具体的には、[リスト 5.16](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#code-footer_css)の内容を1つずつ変換していき、[リスト 5.19](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#code-refactored_scss)のようにしてみてください。
```css
@import "bootstrap-sprockets";
@import "bootstrap";

$gray-medium-light: #eaeaea;

/* universal */

body {
  padding-top: 60px;
}

section {
  overflow: auto;
}

textarea {
  resize: vertical;
}

.center {
  text-align: center;
  h1 {
    margin-bottom: 10px;
  }
}


/* typography */

h1, h2, h3, h4, h5, h6 {
  line-height: 1;
}

h1 {
  font-size: 3em;
  letter-spacing: -2px;
  margin-bottom: 30px;
  text-align: center;
}

h2 {
  font-size: 1.2em;
  letter-spacing: -1px;
  margin-bottom: 30px;
  text-align: center;
  font-weight: normal;
  color: $gray-light;
}

p {
  font-size: 1.1em;
  line-height: 1.7em;
}

/* header */

#logo {
  float: left;
  margin-right: 10px;
  font-size: 1.7em;
  color: $white;
  text-transform: uppercase;
  letter-spacing: -1px;
  padding-top: 9px;
  font-weight: bold;
  &:hover {
    color: $white;
    text-decoration: none;
  }
}

/* footer */

footer {
  margin-top: 45px;
  padding-top: 5px;
  border-top: 1px solid $gray-medium-light;
  color: $gray-light;
  a {
    color: $gray;
    &:hover {
      color: $gray-darker;
    }
  }
  small {
    float: left;
  }
  ul {
    float:right;
    list-style: none;
    li {
      float: left;
      margin-left: 15px;
    }
  }
}
```
